name: BrickLinux2.0 Builder2.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure
        run: sudo chmod 755 ./configure && ./configure
      - name: grub
        run: sudo apt-get install mtools && cd build_root && sudo mknod -m 600 ./dev/console c 5 1 && sudo mknod -m 666 ./dev/null c 1 3 && cd .. && i686-elf-gcc -nostdlib -ffreestanding -no-pie src/init.c src/start.S -o build_root/init && sudo grub-mkrescue -o OSOut/BrickLinux2.iso build_root

      - name: Download Output
        uses: actions/upload-artifact@v2
        with:
          name: BrickLinux2
          path: OSOut
