# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: grub
        run: sudo apt-get install mtools && cd build_root && sudo mknod -m 600 ./dev/console c 5 1 && sudo mknod -m 666 ./dev/null c 1 3 && sudo cp /boot/initrd.img-5.13.0-1021-azure boot/initrd.img && sudo cp /boot/vmlinuz-5.13.0-1021-azure boot/vmlinuz && cd .. && gcc -nostdlib -ffreestanding -no-pie src/init.c src/start.S -o build_root/sbin/init && sudo grub-mkrescue -o OSOut/BrickLinux2.iso build_root

      - name: Download Output
        uses: actions/upload-artifact@v2
        with:
          name: BrickLinux2
          path: OSOut
